M48
; DRILL file {KiCad 7.0.7} date Thu Mar 21 15:18:13 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-21T15:18:13+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
%
G90
G05
T1
X6.8622Y-3.5476
X6.8622Y-3.7752
T2
X5.589Y-3.4567
X5.789Y-3.4167
X5.789Y-3.4967
T0
M30
